### ISSUE TITLE
Ubuntu18.04 从剪切版中解析订阅链接 显示：操作无效

### ISSUE THREAD

**Issue by MJhula** [nojsja/shadowsocks-electron#10]

**Comment by nojsja** [comment]
@MJhula 你用的哪家服务商，我去试试，我用的泡芙和速蛙都没啥问题

**Comment by MJhula** [comment]
那可能是我的订阅链接有问题，我去搞个你说的速蛙试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月25日(星期三) 上午9:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nojsja/shadowsocks-electron] Ubuntu18.04 从剪切版中解析订阅链接 显示：操作无效 (Issue #10)





 
@MJhula 你用的哪家服务商，我去试试，我用的泡芙和速蛙都没啥问题

**Comment by dragen1860** [comment]
+1, 有些服务商的订阅链接可以直接用，但是有些的显示"操作无效“”。
我的理解，应该是shadowsocks-electron的兼容性不够，因为这些订阅链接再windows平台都是可以用的，但是Ubuntu下面，有些就用不了，希望能够改善支持程度。
