### ISSUE TITLE
Feature Request: Add a button in main UI or add option in menu bar to easily connect or disconnect selected  server.

### ISSUE THREAD

**Issue by Mor4eza** [nojsja/shadowsocks-electron#12]
Feature Request: Add a button in the main UI or an option in the menu bar to easily connect or disconnect the selected server.

Thank you for this great application.

**Comment by nojsja** [comment]
Sounds good, thanks for the suggestion, this feature will be added in the next release.

**Comment by lgg** [comment]
@nojsja God Bless you! I just wanna to say thank you for this app.

**Comment by nojsja** [comment]
This feature is supported on v1.2.1.

**Comment by Mor4eza** [comment]
> This feature is supported on v1.2.1.

amazing news 🤩
thanks🙏🏻
