### ISSUE TITLE
do not support windows, why? how can it be called cross-platform?

### ISSUE THREAD

**Issue by ikebo** [nojsja/shadowsocks-electron#2]

**Comment by nojsja** [comment]
> _No description provided._

需要的话可以支持，考虑到 win上已经有很多类似的软件了，盲目增加一个平台的话增加维护工作量 😁

**Comment by ikebo** [comment]
of course 需要阿。同时支持 windows + mac. 是很大的亮点

**Comment by nojsja** [comment]
Windows platform is supported in v1.1.4.
