### ISSUE TITLE
窗口最小化问题

### ISSUE THREAD

**Issue by jiaweiru** [nojsja/shadowsocks-electron#20]
我在ubuntu22.04上snap store下载的shadowsocks electron，使用时发现最小化窗口之后，窗口就不见了但服务还在后台运行，重新点击图标会闪现出来一个窗口界面并立即消失。
    现在就是如果不小心点到最小化按钮就没办法重新选择代理了

**Comment by nojsja** [comment]
>     我在ubuntu22.04上snap store下载的shadowsocks electron，使用时发现最小化窗口之后，窗口就不见了但服务还在后台运行，重新点击图标会闪现出来一个窗口界面并立即消失。
>     现在就是如果不小心点到最小化按钮就没办法重新选择代理了

我排查一下，你可以换用 deb 版本的看看有无此问题

**Comment by jiaweiru** [comment]
我发现机器重启后就恢复正常了，右上角图标可以正常使用。
谢谢你的回复
