### ISSUE TITLE
kali上v2ray运行报错

### ISSUE THREAD

**Issue by saaspeter** [nojsja/shadowsocks-electron#27]
您好，这个工具非常好，界面简洁易用。但我在kali上使用碰到一个问题，UI上显示server是online状态，但是却连接不了外网，从后台log看似乎是v2ray加载错误，我开始用系统的v2ray也连不上，后来用了v2ray的github上的1.3.2 linux amd64版本，也还是不行，以下是后台log，请帮忙分析下哪里出错了，谢谢！

info: 2/10/2023, 11:55:34 AM -  2023-02-10 11:55:34 INFO: plugin "/home/kali/.config/shadowsocks-electron/runtime/bin/linux/x64/v2ray-plugin" enabled
 2023-02-10 11:55:34 INFO: initializing ciphers... chacha20-ietf-poly1305

>> SocketTransfer listening on port:  1080
StartClusterInterceptor: after
info: 2/10/2023, 11:55:34 AM -  2023-02-10 11:55:34 INFO: listening at 127.0.0.1:1081
2023/02/10 11:55:34 [Warning] V2Ray 4.38.3 started

child.stderr.on.data >> 
**_error: 2/10/2023, 11:55:34 AM - 2023/02/10 11:55:34 V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.15 linux/amd64)_**

2023/02/10 11:55:34 A unified platform for anti-censorship.

info: 2/10/2023, 11:55:35 AM - Started ss-local
info: 2/10/2023, 11:55:44 AM - 2023/02/10 11:55:44 127.0.0.1:58166 accepted tcp:127.0.0.1:0

>> health check result:  false

**Comment by nojsja** [comment]
我之前用作者发布的版本也不行，后来在自己电脑上编译了几个版本尝试，发现下面的是可用的：
```sh
./v2ray-plugin --version                                               2 ↵
v2ray-plugin v1.3.1
Go version go1.14.3
Yet another SIP003 plugin for shadowsocks
```
看下这个仓库 [nojsja/v2ray](https://github.com/nojsja/v2ray-plugin/releases/tag/1.3.1)下的可用不，不行的话你可以尝试用 go1.14.3 自己编译一下。

**Comment by saaspeter** [comment]
感谢。上面仓库中的也不行。后面我再在kali编译试试。

**Comment by morningwn** [comment]
大哥自己编译的咋样？我的Ubuntu 22.04.1 LTS也是这样～

**Comment by saaspeter** [comment]
@morningwn , 不好意思我没有编译。我用了proxy的方式连接了，我的kali是虚拟机，我的SS运行在宿主机上，所以我把宿主机的SS的监听IP改为0.0.0.0，在Kali上用宿主机的ip作为proxy来使用了，kali上就没运行SS client了。（在我的Mac上，只有1.9.4才支持0.0.0.0的，1.10失败。还是很感谢这个project owner，使用体验很棒）
