### ISSUE TITLE
1.2.3版本在windows10平台上无法正常打开google

### ISSUE THREAD

**Issue by wshwb** [nojsja/shadowsocks-electron#33]
1.2.3版本在windows10平台上，设置完服务器地址端口等，无法正常打开google，百度。关闭shadowsocks-electron后可以正常打开百度。
我确定我设置的服务器地址、端口等都是正确的，我用另一个ssr客户端可以正常打开google，俩个客户端都是相同的配置参数。

**Comment by wshwb** [comment]
Linux上可以用吗？我找了好久都没找到在linux上可以正常使用的SSR客户端，我现在只有在Windows上才可以访问google。有没有好心人指点迷津？？

**Comment by nojsja** [comment]
最好贴一下客户端的运行日志，三个平台都能用

**Comment by wshwb** [comment]
### 打开后设置为全局，不能打开google，设置为PAC后可以打开google，日志如下
{"level":"info","message":"appDataPath: C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron"}
{"level":"info","message":"pathRuntime: C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\"}
{"level":"info","message":"pathExecutable: C:\\Users\\ACER\\AppData\\Local\\Programs\\Shadowsocks Electron"}
{"level":"info","message":"Closing PAC server"}
{"level":"info","message":"Generating full PAC file..."}
{"level":"info","message":"Starting PAC server"}
{"level":"info","message":"Watching PAC file C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\pac\\gfwlist-user.txt..."}
{"level":"info","message":"Watching PAC file C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\pac\\gfwlist.txt..."}
{"level":"info","message":"Generated done."}
{"level":"info","message":"Set proxy on"}
{"level":"info","message":"Exec command: C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\bin\\win32\\x64\\ssr-local.exe -s 45.76.12.160 -p 11900 -b 127.0.0.1 -l 1081 -k xxxxx-m none -t 60 -o plain -O origin -v"}
{"level":"error","message":" 2023-04-12 21:55:43 INFO: initializing ciphers... none\r\n"}
{"level":"error","message":" 2023-04-12 21:55:43 INFO: listening at 127.0.0.1:1081\r\n"}
{"level":"info","message":"Started ssr-local"}
{"level":"info","message":"Closing PAC server"}
{"level":"info","message":"Closing PAC server"}
{"level":"info","message":"UnWatching PAC file C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\pac\\gfwlist-user.txt..."}
{"level":"info","message":"Set proxy off"}
{"level":"info","message":"Exited C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\bin\\win32\\x64\\ssr-local.exe with error  2023-04-12 21:55:43 INFO: listening at 127.0.0.1:1081\r\n"}
{"level":"info","message":">> Killed ss-local"}
{"level":"info","message":"Set proxy off"}
{"level":"info","message":"Set proxy on"}
{"level":"info","message":"Exec command: C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\bin\\win32\\x64\\ssr-local.exe -s 45.76.12.160 -p 11900 -b 127.0.0.1 -l 1081 -k XXXXX-m none -t 60 -o plain -O origin -v"}
{"level":"error","message":" 2023-04-12 21:55:46 INFO: initializing ciphers... none\r\n"}
{"level":"error","message":" 2023-04-12 21:55:46 INFO: listening at 127.0.0.1:1081\r\n"}
{"level":"info","message":"Started ssr-local"}
{"level":"error","message":" 2023-04-12 21:55:56 INFO: connect to www.google.com:80 via 45.76.12.160:11900\r\n 2023-04-12 21:55:56 INFO: server_info host 45.76.12.160\r\n"}
{"level":"info","message":"Started ssr-local"}
{"level":"info","message":"Closing PAC server"}
{"level":"info","message":"Starting PAC server"}
{"level":"info","message":"Watching PAC file C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\pac\\gfwlist-user.txt..."}
{"level":"info","message":"Watching PAC file C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\pac\\gfwlist.txt..."}
{"level":"info","message":"Set proxy on"}
{"level":"info","message":"Exited C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\bin\\win32\\x64\\ssr-local.exe with error  2023-04-12 21:55:56 INFO: connect to www.google.com:80 via 45.76.12.160:11900\r\n 2023-04-12 21:55:56 INFO: server_info host 45.76.12.160\r\n"}
{"level":"info","message":">> Killed ss-local"}
{"level":"info","message":"Set proxy off"}
{"level":"info","message":"Generating full PAC file..."}
{"level":"info","message":"Generated done."}
{"level":"info","message":"Set proxy on"}
{"level":"info","message":"Exec command: C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\bin\\win32\\x64\\ssr-local.exe -s 45.76.12.160 -p 11900 -b 127.0.0.1 -l 1081 -k XXXXX-m none -t 60 -o plain -O origin -v"}
{"level":"error","message":" 2023-04-12 21:56:11 INFO: initializing ciphers... none\r\n"}
{"level":"error","message":" 2023-04-12 21:56:11 INFO: listening at 127.0.0.1:1081\r\n"}
{"level":"info","message":"Started ssr-local"}
{"level":"error","message":" 2023-04-12 21:56:19 INFO: connect to www.google.com:443 via 45.76.12.160:11900\r\n 2023-04-12 21:56:19 INFO: server_info host 45.76.12.160\r\n 2023-04-12 21:56:19 INFO: connect to www.gstatic.com:443 via 45.76.12.160:11900\r\n"}
{"level":"error","message":" 2023-04-12 21:56:19 INFO: server_info host 45.76.12.160\r\n"}
{"level":"info","message":"Started ssr-local"}
{"level":"error","message":" 2023-04-12 21:56:20 INFO: connect to lh3.google.com:443 via 45.76.12.160:11900\r\n 2023-04-12 21:56:20 INFO: server_info host 45.76.12.160\r\n"}
{"level":"error","message":" 2023-04-12 21:56:21 INFO: connect to aa.google.com:443 via 45.76.12.160:11900\r\n 2023-04-12 21:56:21 INFO: server_info host 45.76.12.160\r\n"}
{"level":"info","message":"Started ssr-local"}
{"level":"error","message":" 2023-04-12 21:56:21 INFO: connect to lh3.googleusercontent.com:443 via 45.76.12.160:11900\r\n 2023-04-12 21:56:21 INFO: server_info host 45.76.12.160\r\n"}
{"level":"info","message":"Started ssr-local"}
{"level":"error","message":" 2023-04-12 21:56:22 INFO: connect to www.google.com:80 via 45.76.12.160:11900\r\n 2023-04-12 21:56:22 INFO: server_info host 45.76.12.160\r\n"}
{"level":"info","message":"Started ssr-local"}
{"level":"error","message":" 2023-04-12 21:56:25 INFO: connect to ogs.google.com:443 via 45.76.12.160:11900\r\n 2023-04-12 21:56:25 INFO: server_info host 45.76.12.160\r\n"}
{"level":"error","message":" 2023-04-12 21:56:25 INFO: connect to play.google.com:443 via 45.76.12.160:11900\r\n 2023-04-12 21:56:25 INFO: server_info host 45.76.12.160\r\n"}
{"level":"info","message":"Started ssr-local"}
{"level":"info","message":"App will quit. Cleaning up..."}
{"level":"info","message":"Exited C:\\Users\\ACER\\AppData\\Roaming\\shadowsocks-electron\\runtime\\bin\\win32\\x64\\ssr-local.exe with error  2023-04-12 21:56:25 INFO: connect to play.google.com:443 via 45.76.12.160:11900\r\n 2023-04-12 21:56:25 INFO: server_info host 45.76.12.160\r\n"}
{"level":"info","message":">> Killed ss-local"}
{"level":"info","message":"Set proxy off"}
谢谢！

**Comment by wshwb** [comment]
我刚刚下载了1.2.3.AppImage在Fedora37系统内测试了，第一次可以打开软件，后面打开Appimage就闪退，打不开了，请问这是怎么回事啊？

**Comment by nojsja** [comment]
Fedora就没测试，使用 Clash 吧，全平台的

**Comment by wshwb** [comment]
谢谢，已经在fedora37上用clash连上google了。
