### ISSUE TITLE
Feature request: minimize to the system tray at startup

### ISSUE THREAD

**Issue by undnull** [nojsja/shadowsocks-electron#9]
An option of some sorts that allows you (at least on Linux) to minimize the client to the tray as soon as it starts

**Comment by nojsja** [comment]
Sounds good, soon at next release.

**Comment by nojsja** [comment]
> An option of some sorts that allows you (at least on Linux) to minimize the client to the tray as soon as it starts

Feature already supported, checkout [v1.1.11](https://github.com/nojsja/shadowsocks-electron/releases/tag/v1.1.11).

**Comment by undnull** [comment]
Awesome! Big thanks!
